version: "3"

services:
  php-rest-staging:
    build:
      context: ./php-rest
      args:
        buildno: ${BUILD_NUMBER}
    image: ${REGISTRY_SLASH-127.0.0.1:5000}/php-rest:${BUILD_NUMBER-latest}
    depends_on:
      - db-staging
    environment:
      - DB_USER=root
      - DB_PASS=my-staging-pw
      - DB_HOST=db
    deploy:
      replicas: 4
    ports:
    - "1010:80"

  webui-staging:
    build: flaskui/
    image: ${REGISTRY_SLASH-127.0.0.1:5000}/webui:${BUILD_NUMBER-latest}
    depends_on:
      - php-rest-staging
    deploy:
      replicas: 4
    ports:
    - "8000:8080"

  db-staging:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=my-staging-pw
      
